name: Render still
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Which text should it say?"
        required: true
        default: "Welcome to Remotion"
      description:
        description: "Which subtitle should it be?"
        required: true
        default: "Enter your subtitle here!"
jobs:
  render:
    name: Render still
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: npm run build -- --props="./input-props.json"
      - uses: actions/upload-artifact@v2
        with:
          name: still.png
          path: out/still.png
